//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardfileDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardfileDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon cardfile {
            get {
                object obj = ResourceManager.GetObject("cardfile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cardfileLogo {
            get {
                object obj = ResourceManager.GetObject("cardfileLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageName=English (United States)
        ///ProgramName=Cardfile.NET
        ///ShortName=Cardfile
        ///TitleFormat={0} - {1}
        ///
        ///# Generic
        ///OK=OK
        ///Cancel=Cancel
        ///
        ///# Other strings
        ///
        ///OpenFilter=Cardfile.NET file (*.CRDX)|*.CRDX|Classic Card File (*.CRD)|*.CRD|All files (*.*)|*
        ///SaveFilter=Cardfile.NET file, compressed (*.CRDX)|*.CRDX|Cardfile.NET file (*.CRDX)|*.CRDX|All files (*.*)|*
        ///ImportAttachmentFilter=All files (*.*)|*
        ///ExportAttachmentFilter={1} (*{0})|*{0}|All files (*.*)|*
        ///ExportAttachmentFilterNoExt=All files (*.*) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en_US {
            get {
                return ResourceManager.GetString("lang_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageName=Suomi (Finnish)
        ///ProgramName=Kortisto (Cardfile.NET)
        ///ShortName=Kortisto
        ///TitleFormat={0} - {1}
        ///
        ///# Generic
        ///OK=OK
        ///Cancel=Peruuta
        ///
        ///# Other strings
        ///
        ///OpenFilter=Cardfile.NET-kortistotiedosto (*.CRDX)|*.CRDX|Klassinen kortistotiedosto (*.CRD)|*.CRD|Kaikki tiedostot (*.*)|*
        ///SaveFilter=Cardfile.NET-kortistotiedosto, pakattu (*.CRDX)|*.CRDX|Cardfile.NET-kortistotiedosto (*.CRDX)|*.CRDX|Kaikki tiedostot (*.*)|*
        ///ImportAttachmentFilter=Kaikki tiedostot (*.*)|*
        ///ExportAttachmentFilter={1} (*{0})| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_fi_FI {
            get {
                return ResourceManager.GetString("lang_fi-FI", resourceCulture);
            }
        }
    }
}
